---
title: "Paired AUROC"
---

```{r, include = FALSE}
knitr::opts_chunk$set(
    collapse = TRUE,
    comment = "#>"
)
```

```{r setup}
options(warn = 1)
library(restrictedROC)
library(MASS) # for rnbinom
main_plotname <- "res/paper/auroc_paired"
dir.create("res/paper", recursive = TRUE)
```

```{r}
set.seed(1)
n <- 100
x <- rnbinom(n, mu = 10, size = 1)
y <- rnbinom(n, mu = 10, size = 1)
```
    
```{r, Use dataMelanoma}
library(dplyr)
outdir <- "intermediate_data/li-2019"
dir.create(outdir, recursive = TRUE)
li_all_data_measurements <- dataMelanoma::li2019_measurements
```

```{r, helper functions}
testing_timepoints_fun <- function(data_named_timepoints,
                                   testing_fun,
                                   bind_format_reslist,
                                   verbose = TRUE,
                                   save_intermediate_file = "intermediate_data/res_rroc_test.RDS",
                                   ...) {
    res_rroc_test <- list()
    for (timepoint1 in names(data_named_timepoints)) {
        for (timepoint2 in names(data_named_timepoints)) {
            cat(timepoint1, timepoint2)
            if (timepoint1 == timepoint2) {
                cat("  skipped\n")
                next
            }
            cat("\n")
            data_tp1 <- data_named_timepoints[[timepoint1]]
            data_tp2 <- data_named_timepoints[[timepoint2]]
            if (!all(colnames(data_tp1) == colnames(data_tp2))) {
                stop("The order of the features is not the same in both matrices")
            }
            tmp_reslist <- list()
            for (feature in colnames(data_tp1[, -1])) {
                cat("  ", feature, "\n")
                if (!all(data_tp1[[1]] == data_tp2[[1]])) {
                    stop("The order of the samples is not the same in both matrices")
                }
                data_tp1_tp2 <- data.frame(
                    "tp1" = data_tp1[[feature]],
                    "tp2" = data_tp2[[feature]]
                )
                data_tp1_tp2_nona <- na.omit(data_tp1_tp2)
                if (nrow(data_tp1_tp2_nona) < 2) {
                    cat("    ", "Too few samples, skipping\n")
                    next
                }
                tmp_reslist[[feature]] <- testing_fun(
                    response = c(rep(timepoint1, nrow(data_tp1_tp2_nona)), rep(timepoint2, nrow(data_tp1_tp2_nona))),
                    predictor = c(data_tp1_tp2_nona[[1]], data_tp1_tp2_nona[[2]]),
                    positive_label = timepoint2,
                    ...
                )
                tmp_reslist[[feature]][["avg.FC"]] <- mean(data_tp1_tp2_nona[[2]]) - mean(data_tp1_tp2_nona[[1]])
            }
            res_rroc_test[[paste0(timepoint1, "_", timepoint2)]] <- bind_format_reslist(tmp_reslist)
            if (!is.na(save_intermediate_file)) {
                qs::qsave(res_rroc_test, file = save_intermediate_file)
            }
        }
    }
    return(res_rroc_test)
}


test_timepoints_fun <- function(
    data_named_timepoints,
    test_fun = t.test,
    verbose = TRUE,
    save_intermediate_file = "intermediate_data/res_rroc_test.RDS",
    ...) {
    return(
        testing_timepoints_fun(
            data_named_timepoints = data_named_timepoints,
            testing_fun = function(response, predictor, positive_label, ...) {
                return(test_fun(
                    x = predictor[response == positive_label],
                    y = predictor[response != positive_label],
                    ...
                ))
            },
            bind_format_reslist = function(x) {
                tmp <- tibble::as_tibble(do.call(rbind, lapply(
                    x, function(x) {
                        return(c(
                            "neglog_p.value" = -log10(x$p.value),
                            "p.value" = x$p.value,
                            "t" = x$statistic[[1]],
                            "avg.FC" = x[["avg.FC"]]
                        ))
                    }
                )))
                tmp[["q.value"]] <- p.adjust(tmp[["p.value"]], method = "BH")
                tmp[["negL10_q.value"]] <- -log10(tmp[["q.value"]])
                tmp[["feature"]] <- names(x)
                return(tmp)
            },
            verbose = verbose,
            save_intermediate_file = save_intermediate_file,
            ...
        )
    )
}
```

```{r paired tests}
# install.packages("qs")
li_all_data_ttests_paired <- lapply(
    li_all_data_measurements,
    test_timepoints_fun,
    save_intermediate_file = file.path(outdir, "res_t_test.qs"),
    test_fun = t.test,
    paired = TRUE, var.equal = TRUE
)
li_all_data_ttests_unpaired <- lapply(
    li_all_data_measurements,
    test_timepoints_fun,
    save_intermediate_file = file.path(outdir, "res_t_test_unpaired.qs"),
    test_fun = t.test,
    paired = FALSE, var.equal = TRUE
)


li_all_data_wilcox_unpaired <- lapply(
    li_all_data_measurements,
    test_timepoints_fun,
    save_intermediate_file = file.path(outdir, "res_wilcox_test_unpaired.qs"),
    test_fun = wilcox.test,
    paired = FALSE
)
li_all_data_wilcox_paired <- lapply(
    li_all_data_measurements,
    test_timepoints_fun,
    save_intermediate_file = file.path(outdir, "res_wilcox_test_paired.qs"),
    test_fun = wilcox.test,
    paired = TRUE
)

li_all_data_wilcoxDIFF_unpaired <- lapply(
    li_all_data_measurements,
    test_timepoints_fun,
    save_intermediate_file = file.path(outdir, "res_wilcox_test_unpairedDIFF.qs"),
    test_fun = function(x, y, ...) {
        # https://en.wikipedia.org/wiki/Wilcoxon_signed-rank_test
        wilcox.test(x - y, paired = FALSE, )
    }
)
```

```{r, Investigate results}
library(qs)
res <- list(
    "t_paired" = qs::qread(file.path(outdir, "res_t_test.qs")),
    "t_unpaired" = qs::qread(file.path(outdir, "res_t_test_unpaired.qs")),
    "w_paired" = qs::qread(file.path(outdir, "res_wilcox_test_paired.qs")),
    "w_unpaired" = qs::qread(file.path(outdir, "res_wilcox_test_unpaired.qs")),
    "w_diff_unpaired" = qs::qread(file.path(outdir, "res_wilcox_test_unpairedDIFF.qs"))
)
```

```{r, Plot results}
library(ggplot2)

for (data_x in names(res[[1]])) {
    plots <- lapply(names(res), function(x) {
        ggplot(res[[x]][[data_x]], aes(x = avg.FC, y = negL10_q.value, label = feature)) +
            ggtitle(paste0(x, " ", data_x), subtitle = paste0("Paired t-test")) +
            geom_point()
        # geom_text_repel()
    })

    w_tmp <- res[["w_paired"]][["baseline_week 4"]]
    w_tmp[["test"]] <- "w_paired"
    w_diff_tmp <- res[["w_diff_unpaired"]][["baseline_week 4"]]
    w_diff_tmp[["test"]] <- "w_diff_unpaired"

    w_tmp[["p.value"]] - w_diff_tmp[["p.value"]]

    pdf("removeme.pdf", height = 25)
    patchwork::wrap_plots(plots, ncol = 1, nrow = length(names(res)))
    print(
        ggplot2::qplot(
            w_tmp[["p.value"]],
            w_diff_tmp[["p.value"]]
        )
    )
    dev.off()
}
```

```{r, Restriction on the differences between pairs}

```