---
title: "Example distributions"
---

```{r, include = FALSE}
knitr::opts_chunk$set(
    collapse = TRUE,
    comment = "#>"
)
```

```{r setup}
options(warn = 1)
library(restrictedROC)
library(MASS) # for rnbinom
```

```{r, fig.fullwidth=TRUE, fig.width=5, fig.height=5}
##### poisson
# pdf("removeme.pdf")
n <- 1000 # Number of values

rroc_theo <- plot_rROC_theoretical(
    qnorm_positive = function(x) {
        retvec <- numeric(length(x))
        retvec_parts <- split(
            seq_along(retvec),
            sample(1:3, length(retvec), replace = TRUE, prob = c(.2, .1, .7))
        )
        dists <- list(
            function(x) qunif(x, min = 0.1, max = 0.25),
            function(x) qunif(x, min = 0.25, max = 1),
            function(x) qunif(x, min = 1, max = 1.25)
        )
        for (dist_i in seq_along(dists)) {
            retvec[retvec_parts[[dist_i]]] <- dists[[dist_i]](x[retvec_parts[[dist_i]]])
        }
        return(retvec)
    },
    qnorm_negative = function(x) qunif(x, min = 0, max = 1),
    n_positive = n,
    n_negative = n,
    return_all = TRUE,
    xmin = 0, xmax = 1.5
)
print(rroc_theo[["rroc"]][["single_rROC"]][["pROC_full"]])
print(rroc_theo[["rroc"]][["plots"]])
# dev.off()
```
