---
title: "TODO"
---

```{r, include = FALSE}
knitr::opts_chunk$set(
    collapse = TRUE,
    comment = "#>"
)
```




```{r setup}
options(warn = 1)
library(restrictedROC)
```
```{r data}
outdir <- "intermediate_data/2022-zhang"
library(future)
plan(multisession)
# data("dataMelanoma")
# This feature selection follows exactly "data-raw/2022-Zhang-GenomeMedicine/data/GM/Code/Model_Stem.Sig.R"
# Note that NOT all of the features from zhang2022_Stem.Sig are in the dataset!
train_stemsig <- dataMelanoma::zhang2022_training[
    ,
    colnames(dataMelanoma::zhang2022_training) %in% c("response", dataMelanoma::zhang2022_Stem.Sig)
]
for (n_permutations in c(50e3, 25e3, 10e3)) {
    tmp <- restrictedROC::rROC(
        x = train_stemsig,
        dependent_vars = "response",
        # With NULL, all features except the dependent_vars are used
        independent_vars = NULL,
        n_permutations = n_permutations,
        parallel_permutations = TRUE,
        positive_label = "R",
        save_intermediate = TRUE,
        # ".qs" is appended automatically to make clear it was saved with qs::qsave()
        save_path = file.path(outdir, paste0("rroc_training_", n_permutations))
        # save_path = file.path(outdir, "rroc_training.qs")
    )
}

rroc_zhang <- qs::qread(file.path(outdir, "rroc_training_50000.qs"))
class(rroc_zhang) <- c("rROC", class(rroc_zhang))  # needed when restrictedROC 3.3.2 (not 3.3.2.0001) is used
s_zhang <- summary(rroc_zhang)
s_zhang[["qval.twoside.max"]] <- p.adjust(s_zhang[["pval.twoside.max"]], method = "BH")
s_zhang[["qval.twoside.global"]] <- p.adjust(s_zhang[["pval.twoside.global"]], method = "BH")
# # A tibble: 4 × 10
#   level_1  level_2 level_3   pval.twoside.max pval.twoside.global n_permutations
#   <chr>    <chr>   <chr>                <dbl>               <dbl>          <dbl>
# 1 response FTH1    permutat…           0.0909              0.273              10
# 2 response EEF1A1  permutat…           0.273               0.0909             10
# 3 response ACTB    permutat…           0.182               0.545              10
# 4 response ACTG1   permutat…           0.818               0.273              10

zhang_significant_restricted <- s_zhang |> 
    dplyr::filter(qval.twoside.max < 0.05)
zhang_additional_significant_features <- s_zhang |>
    dplyr::filter(qval.twoside.max < 0.05, qval.twoside.global > .05) |>
    dplyr::pull(level_2)
```


```{r, plotting results}
library(ggplot2)
pdf(file.path(outdir, "global_max_pval.pdf"))
for (name_x in unique(s_zhang$level_1)) {
    outcomeX_result <- dplyr::filter(s_zhang, level_1 == name_x)

    p1 <- ggplot(outcomeX_result, aes(x = pval.twoside.global, y = pval.twoside.max))
    p2 <- ggplot(outcomeX_result, aes(x = qval.twoside.global, y = qval.twoside.max))
    for (plot_x in list(p1, p2)) {
        print(
            plot_x +
                geom_point() +
                geom_abline(slope = 1, intercept = 0, linewidth = .1) +
                geom_vline(xintercept = 0.05, linetype = "dashed") +
                geom_hline(yintercept = 0.05, linetype = "dashed") +
                scale_x_log10() +
                scale_y_log10() +
                # label gene with q.value < 0.05
                ggrepel::geom_text_repel(
                    data = subset(
                        outcomeX_result,
                        qval.twoside.global > 0.05 & qval.twoside.max < 0.05
                    ),
                    aes(label = level_2),
                    size = 1.5, col = "darkgreen",
                    min.segment.length = 0,
                    max.overlaps = 5
                ) +
                ggtitle(name_x) +
                ggpubr::theme_pubr()
        )
    }
}
dev.off()

# Plotting the restricted ROC
plotlist_1 <- list()
plotlist_2 <- list()
for (feature_outcome in list(
    c("CEACAM6", "response"),
    c("ZMYND11", "response")
)) {
    feature_x <- feature_outcome[[1]]
    outcome_x <- feature_outcome[[2]]
    outcomeX_result_feature <- dplyr::filter(
        s_zhang,
        level_1 == outcome_x,
        level_2 == feature_x
    )
    data_x <- train_stemsig[[feature_x]]
    data_x_noNA <- na.omit(data_x)
    grouped_vals <- split(data_x_noNA, train_stemsig[[outcome_x]])

    rroc_empirical <- restrictedROC::plot_density_rROC_empirical(
        values_grouped = grouped_vals,
        positive_label = "R"
    )
    p1 <- rroc_empirical[["plots"]] + patchwork::plot_annotation(
        title = paste0("Dataset: ", outcome_x, "  --- Feature: ", feature_x)
    )
    plotlist_1 <- c(plotlist_1, list(
        patchwork::wrap_elements(
            p1
        ) + patchwork::wrap_elements(
            gridExtra::tableGrob(
                outcomeX_result_feature,
                theme = gridExtra::ttheme_default(base_size = 4.5)
            )
        ) + patchwork::plot_layout(nrow = 2, height = c(.8, .1))
    ))

    p2 <- restrictedROC::plot_rROC_part(
        rroc_empirical$single_rROC,
        threshold = rroc_empirical$single_rROC[["max_total"]][["threshold"]]
    )
    if (rroc_empirical$single_rROC[["max_total"]][["part"]] == "low") {
        informative_part_plots <- list(p2[["plotlist"]][[5]], p2[["plotlist"]][[6]])
    } else if (rroc_empirical$single_rROC[["max_total"]][["part"]] == "high") {
        informative_part_plots <- list(p2[["plotlist"]][[3]], p2[["plotlist"]][[4]])
    } else {
        informative_part_plots <- list(p2[["plotlist"]][[1]], p2[["plotlist"]][[2]])
    }
    plotlist_2 <- c(plotlist_2, list(
        patchwork::wrap_elements(informative_part_plots[[1]]) +
            patchwork::wrap_elements(informative_part_plots[[2]]) +
            patchwork::plot_layout(nrow = 1) +
            patchwork::plot_annotation(
                title = paste0("Dataset: ", outcome_x, "  --- Feature: ", feature_x)
            )
    ))
}
pdf(file.path(outdir, "rroc_significant.pdf"), width = 8)
print(plotlist_1)
dev.off()
pdf(file.path(outdir, "rroc_significant_partROCs.pdf"), height = 4, width = 8)
print(plotlist_2)
dev.off()
```


```{r, Apply found features to validation and test set}
val_additional <- dataMelanoma::zhang2022_validation[
    ,
    colnames(dataMelanoma::zhang2022_validation) %in% c("response", zhang_additional_significant_features)
]
test_additional <- dataMelanoma::zhang2022_test[
    ,
    colnames(dataMelanoma::zhang2022_test) %in% c("response", zhang_additional_significant_features)
]
datalist <- list("train" = train_stemsig, "val" = val_additional, "test" = test_additional)
pdf("removeme.pdf")
for (feature_x in zhang_additional_significant_features) {
    cat("\n\n\n\n-----------------------------------------------\nFeature: ", feature_x, "\n")
    single_rROC <- restrictedROC::rROC(
        x = train_stemsig,
        dependent_vars = "response",
        independent_vars = feature_x,
        positive_label = "R",
        save_intermediate = FALSE,
        n_permutations = 0,
        return_proc = TRUE
    )
    predicted_tables <- lapply(datalist, function(x) {
        restrictedROC:::predict.restrictedROC(
            object = single_rROC[[1]][[1]][["permutation"]],
            newdata = x,
            newdata_predictor_column = feature_x,
            newdata_response_column = "response",
            pred_high_label = "R",
            pred_low_label = "NR"
        )
        # [c("table_full", "table_restricted", "table_classifiable")]
    })

    # calculate test on contingency tables
    fishertests <- lapply(predicted_tables, function(x) {
        sapply(c("table_full", "table_restricted"), function(y) {
            fisher.test(x = x[[y]])[["p.value"]]
            # chisq.test(x = x[[y]])[["p.value"]]
        }, USE.NAMES = TRUE, simplify = FALSE)
    })
    print(round(unlist(fishertests), 3))

    # calculate aucs
    aucs <- lapply(predicted_tables, function(x) {
        preds <- x[["pred"]]
        kept_preds <- preds[preds[["keep"]], ]
        c(
            "auc.full" =
                pROC::roc(
                    response = preds[["response"]],
                    predictor = preds[["predictor"]]
                )[["auc"]][[1]],
            "auc.restricted" =
                pROC::roc(
                    response = kept_preds[["response"]],
                    predictor = kept_preds[["predictor"]]
                )[["auc"]][[1]]
        )
    })
    print(aucs)

    for (data_name_x in names(datalist)) {
        data_x <- datalist[[data_name_x]]
        print(
            restrictedROC::plot_density_empirical(
                df = split(data_x[[feature_x]], data_x$response)
            ) +
                ggtitle(paste0("Dataset: ", data_name_x, "   feature: ", feature_x)) +
                ggpubr::theme_pubr() +
                geom_vline(
                    xintercept = predicted_tables[[data_name_x]][["threshold_and_restriction"]][["restriction"]],
                    col = "red", linewidth = 1.5
                ) +
                geom_vline(
                    xintercept = predicted_tables[[data_name_x]][["threshold_and_restriction"]][["classification_threshold_restricted"]],
                    col = "blue", linewidth = 1.5
                ) +
                geom_vline(
                    xintercept = predicted_tables[[data_name_x]][["threshold_and_restriction"]][["classification_threshold_full"]],
                    col = "orange", linewidth = .5
                )
        )
    }
}
dev.off()
```

```{r, eval=FALSE}
# nolint start
-----------------------------------------------
Feature:  ZMYND11 
Fri Oct 20 11:16:56 2023      response ZMYND11 
      train.table_full train.table_restricted         val.table_full 
                 0.000                  0.000                  0.467 
  val.table_restricted        test.table_full  test.table_restricted 
                 0.212                  0.676                  0.764 
Setting levels: control = R, case = NR
Setting direction: controls > cases
Setting levels: control = R, case = NR
Setting direction: controls > cases
Setting levels: control = R, case = NR
Setting direction: controls > cases
Setting levels: control = R, case = NR
Setting direction: controls > cases
Setting levels: control = R, case = NR
Setting direction: controls > cases
Setting levels: control = R, case = NR
Setting direction: controls < cases
$train
      auc.full auc.restricted 
     0.5355810      0.6963509 

$val
      auc.full auc.restricted 
     0.5359378      0.5988636 

$test
      auc.full auc.restricted 
     0.5408986      0.4514463 





-----------------------------------------------
Feature:  CEACAM6 
Fri Oct 20 11:16:58 2023      response CEACAM6 
      train.table_full train.table_restricted         val.table_full 
                 0.000                  0.000                  0.466 
  val.table_restricted        test.table_full  test.table_restricted 
                 0.030                  1.000                  0.729 
Setting levels: control = R, case = NR
Setting direction: controls < cases
Setting levels: control = R, case = NR
Setting direction: controls < cases
Setting levels: control = R, case = NR
Setting direction: controls < cases
Setting levels: control = R, case = NR
Setting direction: controls < cases
Setting levels: control = R, case = NR
Setting direction: controls > cases
Setting levels: control = R, case = NR
Setting direction: controls < cases
$train
      auc.full auc.restricted 
     0.5709746      0.6307942 

$val
      auc.full auc.restricted 
     0.4995683      0.6440422 

$test
      auc.full auc.restricted 
     0.5424347      0.4860009 
#nolint end
```
[1]: Lozano, A.X., Chaudhuri, A.A., Nene, A. et al. T cell characteristics associated with toxicity to immune checkpoint blockade in patients with melanoma. Nat Med 28, 353-362 (2022). https://doi.org/10.1038/s41591-021-01623-z 
