---
title: "Vignette 01: rzAUC colors"
---

```{r, include = FALSE}
knitr::opts_chunk$set(
    collapse = TRUE,
    comment = "#>"
)
```

```{r setup}
options(warn = 1)
library(restrictedROC)
```

```{r, fig.fullwidth=TRUE, fig.width=5, fig.height=5}
n_samples <- 100
n_features <- 1
random_df <- data.frame(
    "response" = sample(c(0, 1), size = n_samples, replace = TRUE),
    as.data.frame(matrix(rnorm(n_samples * n_features), nrow = n_samples, ncol = n_features))
)

dependent_vars <- "response"
independent_vars <- colnames(random_df)[colnames(random_df) != "response"]

reslist <- list()
for (dv in dependent_vars) {
    reslist[[dv]] <- list()
    for (iv in independent_vars) {
        cat(date(), "    ", dv, iv, "\n")
        df <- tibble::tibble(
            "response" = random_df[[dv]],
            "predictor" = random_df[[iv]]
        )
        per_resp_list <- split(df$predictor, df$response)
    }
}


# pdf(file.path("res", "rzAUC_colors.pdf"))
print(
    plot_density_rROC_empirical(
        rev(per_resp_list),
        xmin = min(df$predictor),
        xmax = max(df$predictor),
        positive_label = 1,
        direction = "<"
    )
)
print(
    plot_density_rROC_empirical(
        rev(per_resp_list),
        xmin = min(df$predictor),
        xmax = max(df$predictor),
        positive_label = 1,
        direction = "<",
        part_colors = c(high = "#d95f02", low = "#00BFC4")
    )
)
print(
    plot_density_rROC_empirical(
        rev(per_resp_list),
        xmin = min(df$predictor),
        xmax = max(df$predictor),
        positive_label = 1,
        direction = "<",
        part_colors = c(high = "yellow", low = "brown")
    )
)
# dev.off()
```
